apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: podcast-scheduler
  labels:
    app: podcastrs
spec:
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: podcast-scheduler
            image: denyspolitiuk/podcast-scheduler
            env:
            - name: RSS_DATABASE_HOST
              value: "db"
            - name: RSS_DATABASE_PORT
              value: "27017"
          restartPolicy: OnFailure
