---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: podcastrs
spec:
  selector:
    matchLabels:
      app: podcastrs
      tier: api
  replicas: 1
  template:
    metadata:
      labels:
        app: podcastrs
        tier: api
    spec:
      containers:
      - name: podcastrs-podrocket
        image: podrocket-test
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: RSS_DATABASE_HOST
          value: "podcastrs-mongo-pod"
        ports:
        - containerPort: 8000
