---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: podcastrs
spec:
  selector:
    app: podcastrs
    tier: db
  ports:
  - port: 27017
    name: mongo-port
    targetPort: 27017
