---
apiVersion: v1
kind: Pod
metadata:
  name: podcastrs-mongo-express-pod
spec:
  containers:
    - name: podcastrs-mongo-express-pod
      image: mongo-express
      resources:
        requests:
          cpu: 100m
          memory: 500Mi
      env:
      - name: ME_CONFIG_MONGODB_SERVER
        value: podcastrs-mongo-pod
      ports:
      - containerPort: 8081
